// AUTO-GENERATED by scripts/build-extension.js -- do not edit by hand.
// Backend URL is sourced from frontend/.env (REACT_APP_BACKEND_URL) at build time.
// This file is loaded by content_scripts BEFORE gh-review.js, which reads the
// URL from window.__REPUP_REVIEW_CONFIG__.
window.__REPUP_REVIEW_CONFIG__ = {
  "BACKEND_URL": "https://repup-backend-5gl2pr26hq-uc.a.run.app"
};
