/* ================================================================
 * RepUp — GitHub Code Review Sidebar (content script)
 * ----------------------------------------------------------------
 * Injects a Shadow-DOM sidebar into github.com pages that:
 *   • Detects when the user is on a blob (single file) or a PR /files page
 *   • Pulls the actual code via GitHub REST (NOT DOM scraping — survives
 *     any GitHub front-end refactor)
 *   • Hands the code to /api/review on the RepUp backend, which streams
 *     NDJSON events (bugs / security / performance / smells / grade)
 *   • Caches every result keyed by the file's git SHA in
 *     chrome.storage.local so reopening the same file is instant
 *   • Tracks SPA navigation (history.pushState + popstate + a title
 *     MutationObserver fallback) so it switches files without a reload
 *   • Rate-limits: one auto-review per (URL, sha) pair, debounced 1.5s
 *
 * We isolate every byte of DOM/CSS in a Shadow Root so we can't break
 * GitHub's layout, and they can't break ours.
 * ================================================================ */
(function () {
  "use strict";

  if (window.__repupReviewBooted) return;
  window.__repupReviewBooted = true;

  // -------- Config --------------------------------------------------------
  // Backend URL is injected by content/config.js, which is auto-generated by
  // scripts/build-extension.js from frontend/.env (REACT_APP_BACKEND_URL).
  // We never hardcode it here — change the env, re-run the build script.
  const CFG = (typeof window !== "undefined" && window.__REPUP_REVIEW_CONFIG__) || {};
  const BACKEND_URL = (CFG.BACKEND_URL || "").replace(/\/+$/, "");
  if (!BACKEND_URL) {
    // The sidebar refuses to boot without a backend URL — silently doing
    // nothing on every github page would be worse than a clear console error.
    console.error(
      "[RepUp/review] No backend URL configured. " +
        "Run `node scripts/build-extension.js` to regenerate content/config.js " +
        "from frontend/.env (REACT_APP_BACKEND_URL).",
    );
    return;
  }
  const REVIEW_PATH = "/api/review";
  const NAV_DEBOUNCE_MS = 400;
  const CACHE_KEY_PREFIX = "repup_review_v1::"; // chrome.storage.local key prefix
  const CACHE_TTL_MS = 1000 * 60 * 60 * 24 * 7; // 7 days
  const CACHE_MAX_ENTRIES = 100;

  // -------- Tiny utility helpers -----------------------------------------
  const $ = (sel, root) => (root || document).querySelector(sel);
  const log = (...a) => console.debug("[RepUp/review]", ...a);

  function debounce(fn, ms) {
    let t = null;
    return (...args) => {
      if (t) clearTimeout(t);
      t = setTimeout(() => {
        t = null;
        fn(...args);
      }, ms);
    };
  }

  function detectLanguage(filename) {
    const ext = (filename || "").split(".").pop().toLowerCase();
    const map = {
      js: "javascript", jsx: "javascript", mjs: "javascript", cjs: "javascript",
      ts: "typescript", tsx: "typescript",
      py: "python", pyi: "python",
      go: "go", rs: "rust", java: "java", kt: "kotlin", swift: "swift",
      rb: "ruby", php: "php", cs: "csharp", c: "c", h: "c",
      cpp: "cpp", cc: "cpp", cxx: "cpp", hpp: "cpp",
      sh: "bash", bash: "bash", zsh: "bash",
      sql: "sql", html: "html", css: "css", scss: "scss",
      json: "json", yaml: "yaml", yml: "yaml", toml: "toml", md: "markdown",
    };
    return map[ext] || "auto";
  }

  // -------- chrome.storage.local cache (SHA-keyed) -----------------------
  // We persist by file SHA so a closed-and-reopened sidebar on the same
  // file commit hits instantly with NO backend round-trip.
  const cache = {
    async get(sha) {
      if (!sha) return null;
      const k = CACHE_KEY_PREFIX + sha;
      try {
        const obj = await chrome.storage.local.get(k);
        const entry = obj[k];
        if (!entry) return null;
        if (Date.now() - entry.ts > CACHE_TTL_MS) {
          chrome.storage.local.remove(k).catch(() => {});
          return null;
        }
        return entry;
      } catch (e) {
        log("cache.get failed", e);
        return null;
      }
    },
    async put(sha, payload) {
      if (!sha) return;
      const k = CACHE_KEY_PREFIX + sha;
      try {
        await chrome.storage.local.set({ [k]: { ts: Date.now(), ...payload } });
        // LRU-ish trim: if we exceed max entries, drop the oldest.
        const all = await chrome.storage.local.get(null);
        const keys = Object.keys(all).filter((x) => x.startsWith(CACHE_KEY_PREFIX));
        if (keys.length > CACHE_MAX_ENTRIES) {
          keys
            .map((kk) => [kk, all[kk]?.ts || 0])
            .sort((a, b) => a[1] - b[1])
            .slice(0, keys.length - CACHE_MAX_ENTRIES)
            .forEach(([kk]) => chrome.storage.local.remove(kk).catch(() => {}));
        }
      } catch (e) {
        log("cache.put failed", e);
      }
    },
    async clear() {
      try {
        const all = await chrome.storage.local.get(null);
        const keys = Object.keys(all).filter((x) => x.startsWith(CACHE_KEY_PREFIX));
        if (keys.length) await chrome.storage.local.remove(keys);
      } catch (e) {
        log("cache.clear failed", e);
      }
    },
  };

  // -------- GitHub URL → fetch plan --------------------------------------
  // Returns { kind, owner, repo, ref?, path?, prNumber? } or null.
  function parseGhUrl(href) {
    let u;
    try {
      u = new URL(href);
    } catch {
      return null;
    }
    if (u.hostname !== "github.com") return null;
    const parts = u.pathname.split("/").filter(Boolean);
    if (parts.length < 2) return null;
    const [owner, repo, ...rest] = parts;
    // Reserved usernames (settings, marketplace, …) — skip.
    if (["marketplace", "settings", "notifications", "explore", "trending", "topics"].includes(owner)) {
      return null;
    }
    if (rest[0] === "blob" && rest.length >= 3) {
      const ref = rest[1];
      const path = rest.slice(2).join("/");
      return { kind: "blob", owner, repo, ref, path };
    }
    if (rest[0] === "pull" && rest[2] === "files") {
      return { kind: "pr", owner, repo, prNumber: rest[1] };
    }
    return null;
  }

  // -------- GitHub REST helpers ------------------------------------------
  async function ghFetch(apiPath) {
    const r = await fetch(`https://api.github.com${apiPath}`, {
      headers: { Accept: "application/vnd.github+json" },
      credentials: "omit",
    });
    if (!r.ok) {
      const txt = await r.text().catch(() => "");
      const err = new Error(`GitHub ${r.status}: ${txt.slice(0, 140)}`);
      err.status = r.status;
      throw err;
    }
    return r.json();
  }

  async function loadBlobFile(plan) {
    // /repos/{owner}/{repo}/contents/{path}?ref={ref}
    const data = await ghFetch(
      `/repos/${plan.owner}/${plan.repo}/contents/${plan.path}?ref=${encodeURIComponent(plan.ref)}`,
    );
    if (Array.isArray(data) || !data.content) {
      throw new Error("Not a regular file (directory or symlink?)");
    }
    // Base64 with embedded newlines per RFC 2045.
    let code;
    try {
      const bin = atob(data.content.replace(/\s/g, ""));
      // The blob may contain non-ASCII bytes; decode as UTF-8.
      const bytes = new Uint8Array(bin.length);
      for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
      code = new TextDecoder("utf-8").decode(bytes);
    } catch (e) {
      throw new Error(`Decode failed: ${e.message}`);
    }
    return {
      kind: "blob",
      owner: plan.owner,
      repo: plan.repo,
      filename: data.name,
      path: data.path,
      sha: data.sha,
      language: detectLanguage(data.name),
      code,
      sizeBytes: data.size || code.length,
    };
  }

  async function loadPrFiles(plan) {
    // /repos/{owner}/{repo}/pulls/{n}/files
    const arr = await ghFetch(
      `/repos/${plan.owner}/${plan.repo}/pulls/${plan.prNumber}/files?per_page=100`,
    );
    return {
      kind: "pr",
      owner: plan.owner,
      repo: plan.repo,
      prNumber: plan.prNumber,
      files: arr.map((f) => ({
        filename: f.filename,
        sha: f.sha, // blob SHA AT THIS COMMIT — perfect cache key
        status: f.status,
        additions: f.additions,
        deletions: f.deletions,
        patch: f.patch || "",
        rawUrl: f.raw_url,
        language: detectLanguage(f.filename),
      })),
    };
  }

  // -------- /api/review NDJSON consumer ----------------------------------
  // Streams events from the backend and routes them to the sidebar's
  // section renderer. Resolves with the final aggregated payload (which we
  // then persist to the SHA-keyed cache).
  //
  // IMPORTANT: We do NOT call fetch() directly here. github.com ships a
  // strict `connect-src` Content-Security-Policy that does NOT include
  // our backend, and Chrome MV3 content-script fetches DO respect the
  // host page's CSP. So we proxy the request through the background
  // service worker (which has its own extension CSP) via a long-lived
  // chrome.runtime.Port. The SW does the fetch and pipes raw NDJSON
  // chunks back; we parse them line-by-line right here.
  function streamReview({ code, language, filename, context, sha }, onEvent, signal) {
    return new Promise((resolve, reject) => {
      let port;
      try {
        port = chrome.runtime.connect({ name: "repup-review" });
      } catch (e) {
        reject(new Error(`Could not reach the RepUp background worker: ${e.message}. ` +
          `Try reloading the extension at chrome://extensions.`));
        return;
      }

      const aggregate = {
        meta: null,
        bugs: [],
        security: [],
        performance: [],
        smells: [],
        grade: null,
      };
      let buf = "";
      let settled = false;

      const finish = (err, value) => {
        if (settled) return;
        settled = true;
        try { port.disconnect(); } catch (_) { /* already gone */ }
        if (signal) signal.removeEventListener("abort", onAbort);
        err ? reject(err) : resolve(value);
      };

      const onAbort = () => {
        finish(Object.assign(new Error("aborted"), { name: "AbortError" }));
      };
      if (signal) {
        if (signal.aborted) { onAbort(); return; }
        signal.addEventListener("abort", onAbort, { once: true });
      }

      port.onMessage.addListener((msg) => {
        if (!msg) return;
        if (msg.type === "error") {
          finish(new Error(msg.message || "Backend review error"));
          return;
        }
        if (msg.type === "end") {
          finish(null, aggregate);
          return;
        }
        if (msg.type !== "chunk" || typeof msg.text !== "string") return;
        buf += msg.text;
        let nl;
        while ((nl = buf.indexOf("\n")) >= 0) {
          const line = buf.slice(0, nl).trim();
          buf = buf.slice(nl + 1);
          if (!line) continue;
          try {
            const ev = JSON.parse(line);
            if (ev.event === "error") {
              finish(new Error(ev.data?.message || "Backend review error"));
              return;
            }
            if (ev.event in aggregate) aggregate[ev.event] = ev.data;
            try { onEvent && onEvent(ev.event, ev.data, aggregate); } catch (e) { log("onEvent threw", e); }
          } catch (e) {
            log("bad ndjson line", line, e);
          }
        }
      });

      port.onDisconnect.addListener(() => {
        // If the SW disconnects without sending {type:'end'}, treat as error
        // unless we already settled. lastError surfaces "the message port
        // closed before a response was received" type situations.
        const err = chrome.runtime.lastError;
        if (!settled) finish(new Error(err?.message || "Background worker disconnected before completing review."));
      });

      port.postMessage({
        type: "start",
        url: BACKEND_URL + REVIEW_PATH,
        body: { code, language, filename, context, sha },
      });
    });
  }

  // ============================================================
  //                     Shadow DOM SIDEBAR UI
  // ============================================================
  const SIDEBAR_CSS = `
    :host {
      all: initial !important;
      position: fixed !important;
      top: 64px !important;
      right: 0 !important;
      bottom: auto !important;
      left: auto !important;
      width: auto !important;
      height: calc(100vh - 64px) !important;
      max-height: calc(100vh - 64px) !important;
      z-index: 2147483646 !important;
      font-family: ui-sans-serif, -apple-system, "Segoe UI", Roboto, sans-serif !important;
      pointer-events: auto !important;
      display: block !important;
      visibility: visible !important;
      opacity: 1 !important;
      margin: 0 !important;
      padding: 0 !important;
      transform: none !important;
      contain: layout style !important;
    }
    .panel {
      position: relative;
      width: 380px;
      height: 100%;
      background: #09090B;
      color: #fff;
      box-shadow: -8px 0 32px rgba(0, 0, 0, 0.5);
      display: flex; flex-direction: column;
      transform: translateX(0);
      transition: transform 220ms ease;
      border-left: 1px solid rgba(255, 255, 255, 0.08);
    }
    :host([hidden-panel]) .panel { transform: translateX(calc(100% - 36px)); }
    .toggle {
      position: absolute;
      left: -36px; top: 12px;
      width: 36px; height: 76px;
      background: #09090B;
      border: 1px solid rgba(255, 255, 255, 0.1);
      border-right: none;
      border-radius: 12px 0 0 12px;
      color: #CCFF00;
      cursor: pointer;
      display: flex; align-items: center; justify-content: center;
      writing-mode: vertical-rl;
      transform: rotate(180deg);
      font-weight: 800; font-size: 11px; letter-spacing: 0.18em;
      text-transform: uppercase;
      box-shadow: -4px 0 16px rgba(0, 0, 0, 0.4);
    }
    .toggle:hover { background: #141414; }
    header.h {
      padding: 14px 16px 10px;
      border-bottom: 1px solid rgba(255, 255, 255, 0.08);
      display: flex; flex-direction: column; gap: 6px;
    }
    .title-row { display: flex; align-items: center; gap: 8px; }
    .brand {
      font-weight: 900; font-size: 18px; letter-spacing: -0.02em;
    }
    .brand .a { color: #CCFF00; }
    .brand .b { color: #FF5C00; }
    .pill {
      font-family: ui-monospace, Menlo, monospace;
      font-size: 9px; letter-spacing: 0.2em; text-transform: uppercase;
      padding: 2px 8px; border-radius: 999px;
      background: rgba(255, 92, 0, 0.12); color: #FF5C00;
      border: 1px solid rgba(255, 92, 0, 0.3);
    }
    .pill.cached { color: #CCFF00; background: rgba(204,255,0,.1); border-color: rgba(204,255,0,.4); }
    .filename {
      font-family: ui-monospace, Menlo, monospace;
      font-size: 11px; color: rgba(255,255,255,0.7);
      word-break: break-all; line-height: 1.3;
    }
    .file-picker {
      display: flex; gap: 6px; align-items: center; flex-wrap: wrap;
      padding: 10px 16px; border-bottom: 1px solid rgba(255,255,255,0.06);
      background: rgba(255,255,255,0.02);
    }
    .file-picker select {
      flex: 1; min-width: 0;
      background: #141414; color: #fff;
      border: 1px solid rgba(255,255,255,0.1);
      border-radius: 8px; padding: 6px 8px;
      font-family: ui-monospace, Menlo, monospace; font-size: 11px;
    }
    .controls {
      display: flex; gap: 8px; padding: 10px 16px;
      border-bottom: 1px solid rgba(255,255,255,0.06);
    }
    button.btn {
      flex: 1; padding: 9px 12px;
      background: #CCFF00; color: #000;
      border: none; border-radius: 10px;
      font-weight: 800; font-size: 13px; cursor: pointer;
      letter-spacing: 0.02em;
      box-shadow: 0 2px 0 rgba(0,0,0,0.4);
    }
    button.btn:hover { filter: brightness(1.06); }
    button.btn:disabled { opacity: 0.55; cursor: not-allowed; }
    button.btn.ghost {
      background: transparent; color: rgba(255,255,255,0.7);
      border: 1px solid rgba(255,255,255,0.12); flex: 0 0 auto;
    }
    main.body {
      flex: 1; overflow-y: auto; padding: 14px 16px 80px;
      scrollbar-width: thin;
    }
    main.body::-webkit-scrollbar { width: 6px; }
    main.body::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.15); border-radius: 3px; }
    .grade-card {
      display: flex; align-items: center; gap: 14px;
      padding: 14px;
      border-radius: 14px;
      background: linear-gradient(135deg, rgba(204,255,0,0.08), rgba(255,92,0,0.06));
      border: 1px solid rgba(255,255,255,0.08);
      margin-bottom: 14px;
    }
    .grade-letter {
      font-size: 44px; font-weight: 900; line-height: 1;
      letter-spacing: -0.04em;
    }
    .grade-letter.A { color: #CCFF00; }
    .grade-letter.B { color: #5DD3FF; }
    .grade-letter.C { color: #FFD700; }
    .grade-letter.D, .grade-letter.F { color: #FF5C5C; }
    .grade-meta { flex: 1; min-width: 0; }
    .grade-score {
      font-family: ui-monospace, Menlo, monospace;
      font-size: 11px; color: rgba(255,255,255,0.5);
      letter-spacing: 0.1em; text-transform: uppercase;
    }
    .grade-summary { font-size: 13px; line-height: 1.4; margin-top: 2px; color: rgba(255,255,255,0.85); }
    .section { margin-bottom: 14px; }
    .section-head {
      display: flex; align-items: center; gap: 8px;
      font-family: ui-monospace, Menlo, monospace;
      font-size: 10px; letter-spacing: 0.2em; text-transform: uppercase;
      color: rgba(255,255,255,0.55);
      padding: 4px 0 8px;
    }
    .section-head .badge {
      padding: 1px 7px; border-radius: 6px; font-weight: 800;
      background: rgba(255,255,255,0.08);
      color: rgba(255,255,255,0.85);
    }
    .section .icon { font-size: 14px; }
    .finding {
      background: #141414;
      border: 1px solid rgba(255,255,255,0.06);
      border-radius: 12px; padding: 10px 12px; margin-bottom: 8px;
    }
    .finding .title {
      font-weight: 700; font-size: 13px; line-height: 1.3;
      display: flex; gap: 8px; align-items: flex-start;
    }
    .sev {
      flex-shrink: 0;
      font-family: ui-monospace, Menlo, monospace; font-size: 9px;
      letter-spacing: 0.15em; text-transform: uppercase;
      padding: 2px 6px; border-radius: 6px; font-weight: 800;
      margin-top: 1px;
    }
    .sev.high { background: rgba(255,92,92,0.2); color: #FF8E8E; border: 1px solid rgba(255,92,92,0.4); }
    .sev.medium { background: rgba(255,180,0,0.18); color: #FFCC55; border: 1px solid rgba(255,180,0,0.35); }
    .sev.low { background: rgba(255,255,255,0.08); color: rgba(255,255,255,0.6); border: 1px solid rgba(255,255,255,0.1); }
    .line {
      font-family: ui-monospace, Menlo, monospace; font-size: 10px;
      color: rgba(255,255,255,0.4);
      margin-left: 8px; flex-shrink: 0;
    }
    .desc, .sug {
      font-size: 12px; line-height: 1.45; color: rgba(255,255,255,0.78);
      margin-top: 6px;
    }
    .sug { color: #CCFF00; }
    .sug-label {
      font-family: ui-monospace, Menlo, monospace; font-size: 9px;
      letter-spacing: 0.18em; text-transform: uppercase;
      color: rgba(204,255,0,0.6); margin-right: 6px;
    }
    .empty {
      padding: 9px 11px; border-radius: 10px;
      background: rgba(204,255,0,0.06);
      border: 1px dashed rgba(204,255,0,0.25);
      color: rgba(204,255,0,0.85); font-size: 12px;
    }
    .placeholder {
      padding: 22px 14px; text-align: center;
      color: rgba(255,255,255,0.5); font-size: 13px;
      background: rgba(255,255,255,0.02);
      border: 1px dashed rgba(255,255,255,0.1);
      border-radius: 14px;
    }
    .placeholder .accent { color: #CCFF00; font-weight: 700; }
    .skel {
      height: 56px; background: linear-gradient(90deg, #141414 25%, #1d1d1f 50%, #141414 75%);
      background-size: 200% 100%; animation: shimmer 1.4s linear infinite;
      border-radius: 12px; margin-bottom: 8px;
    }
    @keyframes shimmer { 0% { background-position: 200% 0; } 100% { background-position: -200% 0; } }
    .err {
      padding: 10px 12px; border-radius: 10px;
      background: rgba(255,92,92,0.08); color: #FF8E8E;
      border: 1px solid rgba(255,92,92,0.3);
      font-size: 12px; line-height: 1.4;
    }
    .meta-row {
      display: flex; gap: 8px; align-items: center;
      font-family: ui-monospace, Menlo, monospace;
      font-size: 9px; letter-spacing: 0.15em; text-transform: uppercase;
      color: rgba(255,255,255,0.4); margin-top: 8px;
    }
    .footer-spinner {
      display: flex; align-items: center; gap: 8px;
      font-size: 11px; color: rgba(255,255,255,0.5); margin-top: 10px;
    }
    .spinner {
      width: 12px; height: 12px;
      border: 2px solid rgba(255,255,255,0.1);
      border-top-color: #CCFF00;
      border-radius: 50%;
      animation: spin 0.7s linear infinite;
    }
    @keyframes spin { to { transform: rotate(360deg); } }
  `;

  function makeSidebar() {
    const host = document.createElement("div");
    host.id = "repup-review-host";
    // Belt-and-suspenders: set positioning inline with !important so neither
    // GitHub's CSS nor any future :host shadow-rule mishap can knock the
    // sidebar out of its fixed slot. The shadow-DOM :host rule below is the
    // canonical source of truth, but inline styles are guaranteed-applied
    // even before the <style> element parses.
    host.style.cssText = [
      "all: initial",
      "position: fixed !important",
      "top: 64px !important",
      "right: 0 !important",
      "bottom: auto !important",
      "left: auto !important",
      "width: auto !important",
      "height: calc(100vh - 64px) !important",
      "z-index: 2147483646 !important",
      "margin: 0 !important",
      "padding: 0 !important",
      "transform: none !important",
      "pointer-events: auto !important",
      "display: block !important",
      "visibility: visible !important",
      "opacity: 1 !important",
    ].join("; ") + ";";
    // Append to <html> so we sit above <body>'s stacking context. Some sites
    // set transforms on <body> which would create a containing block and
    // break position:fixed; <html> avoids that.
    (document.documentElement || document.body).appendChild(host);
    const root = host.attachShadow({ mode: "open" });

    const style = document.createElement("style");
    style.textContent = SIDEBAR_CSS;
    root.appendChild(style);

    const wrap = document.createElement("div");
    wrap.innerHTML = `
      <div class="panel">
        <button class="toggle" data-action="toggle" title="Toggle RepUp Review">RepUp Review</button>
        <header class="h">
          <div class="title-row">
            <div class="brand"><span class="a">Rep</span><span class="b">Up</span> · Review</div>
            <span class="pill" data-el="status">Idle</span>
            <span class="pill cached" data-el="cache-pill" style="display:none">Cached</span>
          </div>
          <div class="filename" data-el="filename">No file detected on this page.</div>
        </header>
        <div class="file-picker" data-el="file-picker" style="display:none">
          <select data-el="file-select"></select>
        </div>
        <div class="controls">
          <button class="btn" data-action="review" data-el="review-btn">Review with Gemini</button>
          <button class="btn ghost" data-action="rerun" data-el="rerun-btn" title="Force re-run, bypass cache">↻</button>
        </div>
        <main class="body" data-el="body">
          <div class="placeholder">
            Open a <span class="accent">file</span> or a <span class="accent">PR /files</span> tab to get a real-time AI code review.
          </div>
        </main>
      </div>
    `;
    while (wrap.firstChild) root.appendChild(wrap.firstChild);

    const els = {
      panel: $(".panel", root),
      status: $('[data-el="status"]', root),
      cachePill: $('[data-el="cache-pill"]', root),
      filename: $('[data-el="filename"]', root),
      filePicker: $('[data-el="file-picker"]', root),
      fileSelect: $('[data-el="file-select"]', root),
      reviewBtn: $('[data-el="review-btn"]', root),
      rerunBtn: $('[data-el="rerun-btn"]', root),
      body: $('[data-el="body"]', root),
    };
    return { host, root, els };
  }

  // ============================================================
  //                     SIDEBAR CONTROLLER
  // ============================================================
  const ICONS = { bugs: "🐛", security: "🔒", performance: "⚡", smells: "🧹" };
  const LABELS = {
    bugs: "Bugs",
    security: "Security",
    performance: "Performance",
    smells: "Code smells",
  };

  function escapeHtml(s) {
    return String(s || "").replace(
      /[&<>"']/g,
      (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c],
    );
  }

  function renderFinding(f) {
    const sev = (f.severity || "low").toLowerCase();
    const line = f.line != null ? `<span class="line">L${escapeHtml(f.line)}</span>` : "";
    return `
      <div class="finding">
        <div class="title">
          <span class="sev ${sev}">${sev}</span>
          <span style="flex:1">${escapeHtml(f.title || "Untitled")}</span>
          ${line}
        </div>
        ${f.description ? `<div class="desc">${escapeHtml(f.description)}</div>` : ""}
        ${f.suggestion ? `<div class="sug"><span class="sug-label">Fix</span>${escapeHtml(f.suggestion)}</div>` : ""}
      </div>
    `;
  }

  function renderSection(key, findings) {
    const arr = Array.isArray(findings) ? findings : [];
    return `
      <div class="section" data-section="${key}">
        <div class="section-head">
          <span class="icon">${ICONS[key]}</span>
          <span>${LABELS[key]}</span>
          <span class="badge">${arr.length}</span>
        </div>
        ${
          arr.length === 0
            ? `<div class="empty">All clear here ✨</div>`
            : arr.map(renderFinding).join("")
        }
      </div>
    `;
  }

  function renderGrade(g) {
    if (!g) return "";
    const letter = (g.letter || "C").toUpperCase();
    const cls = letter[0]; // A/B/C/D/F
    return `
      <div class="grade-card">
        <div class="grade-letter ${cls}">${escapeHtml(letter)}</div>
        <div class="grade-meta">
          <div class="grade-score">Score · ${escapeHtml(g.score ?? 0)}/100</div>
          <div class="grade-summary">${escapeHtml(g.summary || "")}</div>
        </div>
      </div>
    `;
  }

  function renderSkeletons() {
    return ["bugs", "security", "performance", "smells"]
      .map(
        (k) => `
        <div class="section">
          <div class="section-head">
            <span class="icon">${ICONS[k]}</span>
            <span>${LABELS[k]}</span>
            <span class="badge">…</span>
          </div>
          <div class="skel"></div>
          <div class="skel"></div>
        </div>`,
      )
      .join("");
  }

  // ============================================================
  //                     MAIN APPLICATION
  // ============================================================
  const state = {
    sidebar: null,
    currentUrl: null,
    currentPlan: null,
    currentTarget: null, // { kind, sha, filename, language, code, ... }
    inflight: null, // AbortController for current /api/review request
    autoFiredFor: new Set(), // SHAs we already auto-fired this session
    prFiles: null, // for kind === 'pr'
  };

  function setStatus(text, opts = {}) {
    if (!state.sidebar) return;
    state.sidebar.els.status.textContent = text;
    state.sidebar.els.status.style.background = opts.bg || "rgba(255,92,0,0.12)";
    state.sidebar.els.status.style.color = opts.fg || "#FF5C00";
    state.sidebar.els.status.style.borderColor = opts.bd || "rgba(255,92,0,0.3)";
  }
  function setCachePill(visible) {
    if (state.sidebar) state.sidebar.els.cachePill.style.display = visible ? "inline-block" : "none";
  }

  function setFilename(label) {
    if (state.sidebar) state.sidebar.els.filename.textContent = label;
  }

  function setBody(html) {
    if (state.sidebar) state.sidebar.els.body.innerHTML = html;
  }

  function setReviewEnabled(enabled, label) {
    if (!state.sidebar) return;
    state.sidebar.els.reviewBtn.disabled = !enabled;
    if (label) state.sidebar.els.reviewBtn.textContent = label;
    state.sidebar.els.rerunBtn.disabled = !enabled;
  }

  function showError(msg) {
    setBody(`<div class="err">${escapeHtml(msg)}</div>`);
    setStatus("Error", { bg: "rgba(255,92,92,0.15)", fg: "#FF8E8E", bd: "rgba(255,92,92,0.4)" });
  }

  function paintFinalResult(result, fromCache) {
    const html = [
      renderGrade(result.grade),
      renderSection("bugs", result.bugs),
      renderSection("security", result.security),
      renderSection("performance", result.performance),
      renderSection("smells", result.smells),
      `<div class="meta-row">
         <span>${fromCache ? "From cache" : "Live"} · model gemini-2.5-pro</span>
         ${result.meta?.sha ? `<span style="margin-left:auto">${escapeHtml(result.meta.sha.slice(0, 7))}</span>` : ""}
       </div>`,
    ].join("");
    setBody(html);
    setCachePill(!!fromCache);
    setStatus(fromCache ? "Cached" : "Done", {
      bg: "rgba(204,255,0,0.1)", fg: "#CCFF00", bd: "rgba(204,255,0,0.4)",
    });
  }

  // The progressive renderer keeps a live aggregate and re-renders on each
  // event so partial results paint immediately ("feels fast" UX).
  function makeStreamRenderer() {
    const partial = {
      meta: null, bugs: null, security: null, performance: null, smells: null, grade: null,
    };
    return function (event, data) {
      if (event === "meta") partial.meta = data;
      else if (event in partial) partial[event] = data;

      const sections = ["bugs", "security", "performance", "smells"]
        .map((k) =>
          partial[k] === null
            ? `<div class="section">
                 <div class="section-head"><span class="icon">${ICONS[k]}</span><span>${LABELS[k]}</span><span class="badge">…</span></div>
                 <div class="skel"></div>
               </div>`
            : renderSection(k, partial[k]),
        )
        .join("");
      const head = partial.grade
        ? renderGrade(partial.grade)
        : `<div class="footer-spinner"><span class="spinner"></span> Analyzing with Gemini…</div>`;
      setBody(head + sections);
    };
  }

  // -------- Drive: detect URL, scrape, optionally auto-review ------------
  async function handleNav(forceRerun = false) {
    if (!state.sidebar) return;
    const href = location.href;
    state.currentUrl = href;
    const plan = parseGhUrl(href);

    if (state.inflight) {
      state.inflight.abort();
      state.inflight = null;
    }

    if (!plan) {
      state.currentPlan = null;
      state.currentTarget = null;
      state.prFiles = null;
      state.sidebar.els.filePicker.style.display = "none";
      setFilename("Not a code page.");
      setStatus("Idle", { bg: "rgba(255,255,255,0.06)", fg: "rgba(255,255,255,0.6)", bd: "rgba(255,255,255,0.1)" });
      setCachePill(false);
      setReviewEnabled(false, "Review with Gemini");
      setBody(`
        <div class="placeholder">
          <div style="font-size:15px;font-weight:700;color:#fff;margin-bottom:6px">No code on this page</div>
          <div style="margin-bottom:10px">Open one of these and the sidebar will fire automatically:</div>
          <div style="text-align:left;display:inline-block;font-family:ui-monospace,Menlo,monospace;font-size:11px;line-height:1.7;color:rgba(255,255,255,0.65)">
            • A single file &nbsp;<span class="accent">/blob/&lt;branch&gt;/&lt;path&gt;</span><br>
            • A PR diff &nbsp;<span class="accent">/pull/&lt;n&gt;/files</span>
          </div>
          <div style="margin-top:12px;font-size:11px;color:rgba(255,255,255,0.4)">
            Currently on: <span style="font-family:ui-monospace,Menlo,monospace">${escapeHtml(location.pathname || "/")}</span>
          </div>
        </div>
      `);
      return;
    }

    state.currentPlan = plan;
    setReviewEnabled(false, "Loading file…");
    setStatus("Loading", {});
    setCachePill(false);
    setBody(renderSkeletons());

    try {
      if (plan.kind === "blob") {
        const file = await loadBlobFile(plan);
        state.currentTarget = file;
        state.prFiles = null;
        state.sidebar.els.filePicker.style.display = "none";
        setFilename(`${file.owner}/${file.repo}/${file.path}`);
      } else if (plan.kind === "pr") {
        const pr = await loadPrFiles(plan);
        state.prFiles = pr;
        if (!pr.files.length) {
          setFilename(`${pr.owner}/${pr.repo}#${pr.prNumber} — no files`);
          setReviewEnabled(false, "Nothing to review");
          setBody(`<div class="placeholder">This PR has no changed files.</div>`);
          return;
        }
        // Populate file picker
        state.sidebar.els.fileSelect.innerHTML = pr.files
          .map(
            (f, i) =>
              `<option value="${i}">${escapeHtml(f.filename)} · +${f.additions}/-${f.deletions} (${f.status})</option>`,
          )
          .join("");
        state.sidebar.els.filePicker.style.display = "flex";
        // Default to first file
        await selectPrFile(0, /* autoFire */ !forceRerun);
        return;
      }
    } catch (e) {
      log("scrape failed", e);
      showError(`Couldn't load file: ${e.message}`);
      setReviewEnabled(false, "Review with Gemini");
      return;
    }

    // Blob path: try cache → optionally auto-fire
    setReviewEnabled(true, "Review with Gemini");
    setStatus("Ready", {});
    await maybeAutoReview(forceRerun);
  }

  async function selectPrFile(idx, autoFire) {
    const pr = state.prFiles;
    if (!pr) return;
    const f = pr.files[idx];
    if (!f) return;
    setFilename(`${pr.owner}/${pr.repo}#${pr.prNumber} · ${f.filename}`);
    state.sidebar.els.fileSelect.value = String(idx);

    // For PR files we review the patch (just the diff — fast & focused).
    // If patch is empty (binary or huge), fall back to fetching the raw file.
    let code = f.patch || "";
    let context = "This is a PR diff. Lines starting with '+' are additions, '-' are deletions, ' ' (space) is unchanged context.";
    if (!code && f.rawUrl) {
      try {
        const r = await fetch(f.rawUrl);
        code = await r.text();
        context = "Full file at the PR head commit.";
      } catch (e) {
        log("rawUrl fetch failed", e);
      }
    }
    state.currentTarget = {
      kind: "pr-file",
      owner: pr.owner,
      repo: pr.repo,
      prNumber: pr.prNumber,
      filename: f.filename,
      sha: f.sha,
      language: f.language,
      code,
      context,
    };
    setReviewEnabled(true, "Review with Gemini");
    setStatus("Ready", {});
    setCachePill(false);
    setBody(renderSkeletons());
    if (autoFire) await maybeAutoReview(false);
  }

  async function maybeAutoReview(forceRerun) {
    const t = state.currentTarget;
    if (!t || !t.sha) return;

    // Cache hit → instant render, no backend call.
    if (!forceRerun) {
      const cached = await cache.get(t.sha);
      if (cached?.result) {
        paintFinalResult(cached.result, /* fromCache */ true);
        return;
      }
    }

    // Rate-limit: only auto-fire once per SHA per session.
    if (!forceRerun && state.autoFiredFor.has(t.sha)) {
      // The user already saw this run; just leave the prior result up.
      return;
    }
    state.autoFiredFor.add(t.sha);
    await runReview();
  }

  async function runReview() {
    const t = state.currentTarget;
    if (!t) return;
    if (state.inflight) {
      state.inflight.abort();
      state.inflight = null;
    }
    setReviewEnabled(false, "Reviewing…");
    setStatus("Reviewing", {});
    setCachePill(false);
    setBody(renderSkeletons());

    const ctrl = new AbortController();
    state.inflight = ctrl;
    const renderer = makeStreamRenderer();

    try {
      const aggregate = await streamReview(
        {
          code: t.code || "",
          language: t.language,
          filename: t.filename,
          context: t.context || "",
          sha: t.sha,
        },
        renderer,
        ctrl.signal,
      );
      // Persist to SHA-keyed local cache so reopening this file is instant.
      const result = {
        meta: aggregate.meta,
        bugs: aggregate.bugs || [],
        security: aggregate.security || [],
        performance: aggregate.performance || [],
        smells: aggregate.smells || [],
        grade: aggregate.grade,
      };
      paintFinalResult(result, false);
      await cache.put(t.sha, {
        url: location.href,
        filename: t.filename,
        language: t.language,
        result,
      });
    } catch (e) {
      if (e.name === "AbortError") return;
      log("review failed", e);
      showError(`Review failed: ${e.message}`);
    } finally {
      state.inflight = null;
      setReviewEnabled(true, "Review with Gemini");
    }
  }

  // -------- Sidebar wiring -----------------------------------------------
  function bootSidebar() {
    if (state.sidebar) return;
    state.sidebar = makeSidebar();
    const { host, root, els } = state.sidebar;

    // Persisted collapsed state
    chrome.storage.local.get("repup_review_collapsed").then((o) => {
      if (o.repup_review_collapsed) host.setAttribute("hidden-panel", "");
    }).catch(() => {});

    // IMPORTANT: attach the click listener INSIDE the shadow root, not on
    // the host. When a click event bubbles across a shadow boundary,
    // browsers retarget event.target to the host element (event retargeting),
    // so a host-level listener sees `e.target === host` for every click and
    // `closest('[data-action]')` returns null. Listening inside the shadow
    // root means event.target is the actual clicked element.
    root.addEventListener("click", (e) => {
      const btn = e.target.closest && e.target.closest("[data-action]");
      if (!btn) return;
      const action = btn.getAttribute("data-action");
      if (action === "toggle") {
        if (host.hasAttribute("hidden-panel")) host.removeAttribute("hidden-panel");
        else host.setAttribute("hidden-panel", "");
        chrome.storage.local
          .set({ repup_review_collapsed: host.hasAttribute("hidden-panel") })
          .catch(() => {});
      } else if (action === "review") {
        runReview();
      } else if (action === "rerun") {
        // Force re-run: invalidate cache for current SHA and re-fire.
        const t = state.currentTarget;
        if (t?.sha) {
          chrome.storage.local.remove(CACHE_KEY_PREFIX + t.sha).catch(() => {});
          state.autoFiredFor.delete(t.sha);
        }
        runReview();
      }
    });

    els.fileSelect.addEventListener("change", (e) => {
      selectPrFile(parseInt(e.target.value, 10), true);
    });
  }

  function teardownSidebar() {
    // Cancel any in-flight review and yank the host node.
    try { state.inflight?.abort(); } catch (_) {}
    state.inflight = null;
    if (state.sidebar?.host?.parentNode) {
      try { state.sidebar.host.parentNode.removeChild(state.sidebar.host); } catch (_) {}
    }
    state.sidebar = null;
    state.currentPlan = null;
    state.currentTarget = null;
    state.currentUrl = "";
    state.autoFiredFor = new Set();
  }

  // -------- SPA navigation tracking --------------------------------------
  // GitHub uses turbo/Soft-nav so we never see a real page load. We patch
  // history methods to detect the URL change synchronously and also watch
  // <title> as a robust fallback.
  function installNavObserver() {
    const debounced = debounce(() => handleNav(false), NAV_DEBOUNCE_MS);

    const fireSoon = async () => {
      if (location.href !== state.currentUrl) {
        if (!state.sidebar) {
          const on = await isReviewEnabled();
          if (on) bootSidebar();
        }
        debounced();
      }
    };

    // Patch pushState / replaceState
    for (const method of ["pushState", "replaceState"]) {
      const orig = history[method];
      history[method] = function patched() {
        const ret = orig.apply(this, arguments);
        window.dispatchEvent(new Event("repup:locationchange"));
        return ret;
      };
    }
    window.addEventListener("popstate", fireSoon);
    window.addEventListener("repup:locationchange", fireSoon);

    // <title> mutation as a robust fallback for any nav we might miss.
     const title = document.querySelector("title");
    if (title) {
      const mo = new MutationObserver(fireSoon);
      mo.observe(title, { childList: true });
    }

    // Polling fallback for GitHub turbo nav that bypasses history API
    let _lastPolledUrl = location.href;
    setInterval(() => {
      if (location.href !== _lastPolledUrl) {
        _lastPolledUrl = location.href;
        state.currentUrl = ""; // force fireSoon to pass the URL check
        debounced();
      }
    }, 500);
  }

  // -------- Boot ---------------------------------------------------------
  // Whether the user has the Code Review sidebar enabled. Stored in
  // chrome.storage.local.repup_review_enabled by the side-panel React app
  // (see frontend/src/hooks/useReviewEnabled.js). Default ON.
  async function isReviewEnabled() {
    try {
      const o = await chrome.storage.local.get("repup_review_enabled");
      // Default true when the key has never been set.
      return o.repup_review_enabled !== false;
    } catch (_) {
      return true;
    }
  }

  async function boot() {
    try {
      const on = await isReviewEnabled();
      if (on) {
        bootSidebar();
        installNavObserver();
        // Initial pass — slight delay so the DOM has settled.
        setTimeout(() => handleNav(false), 250);
      } else {
        // Toggle is OFF — install only the nav observer (cheap) and the
        // storage listener; we'll boot the sidebar lazily if the user flips
        // the toggle from the side panel.
        installNavObserver();
      }
      // React in real time when the user flips the toggle from the side panel.
      try {
        chrome.storage.onChanged.addListener((changes, area) => {
          if (area !== "local" || !changes.repup_review_enabled) return;
          const next = changes.repup_review_enabled.newValue !== false;
          if (next && !state.sidebar) {
            bootSidebar();
            setTimeout(() => handleNav(false), 50);
          } else if (!next && state.sidebar) {
            teardownSidebar();
          }
        });
      } catch (_) {
        /* chrome.storage.onChanged not available — degrade silently */
      }
    } catch (e) {
      console.error("[RepUp/review] boot failed", e);
    }
  }

  if (document.readyState === "complete" || document.readyState === "interactive") {
    boot();
  } else {
    window.addEventListener("DOMContentLoaded", boot);
  }
})();
